#!/bin/bash
WEBKIT_REPLACEMENT="com.android.webview"
FDROID="org.fdroid.fdroid org.fdroid.fdroid.privileged"
EXTRA_APP_SELECTION="org.bromite.bromite net.osmand.plus org.videolan.vlc net.gsantner.markor ws.xsoh.etar com.fsck.k9 net.sourceforge.opencamera com.moez.QKSMS org.koreader.launcher.fdroid org.sufficientlysecure.keychain org.documentfoundation.libreoffice com.gsnathan.pdfviewer"
MICROG="GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar additional_repos.xml"
#EAPPS="e_permissions.xml SystemUIWithLegacyRecents OpenWeatherMapWeatherProvider BlissLauncher "
podman run \
	--security-opt label=disable \
	--net host \
	-it --rm \
	-e "BRANCH_NAME=lineage-19.1" \
	-e "DEVICE_LIST=herolte" \
	-e "INCLUDE_PROPRIETARY=false" \
	-e "CUSTOM_PACKAGES=$WEBKIT_REPLACEMENT $FDROID $EXTRA_APP_SELECTION $MICROG $EAPPS " \
	-e "SIGNATURE_SPOOFING=restricted" \
	-e "CLEAN_AFTER_BUILD=false" \
	-e "SKIP_VINTF_PATCH=true" \
	-e "PATCH_BPFL=true" \
	-e "REPOPICK=326385" \
	-v "./src:/srv/src" \
	-v "./zips:/srv/zips" \
	-v "./logs:/srv/logs" \
	-v "./ccache:/srv/ccache" \
	-v "./manifests_herolte_vendor_part:/srv/local_manifests:ro" \
	-v "./userscripts:/root/userscripts:ro" \
	-v "./patches:/patches" \
	-v "/etc/localtime:/etc/localtime:ro" \
docker-lineage-cicd
